### ISSUE TITLE
Project P99

### ISSUE THREAD

**Issue by Relm-Arrowny** [Relm-Arrowny/p99Bluesky#2]
### Goals
Acceptance criteria : 
- [ ] User being able to preform ptychography experiments on p99 using Athena/Bluesky setup

### Tasks
 base on the goals, deduce the tasks required. check them off once they're done
- [ ] Setup Athena communication Channels.
- [ ] Create ophyd-async devices for the hardware on p99
- [ ] Create plan to drive the devices and collect data

**Comment by stan-dot** [comment]
@Relm-Arrowny a [project here](https://github.com/DiamondLightSource/p99-bluesky/projects?query=is%3Aopen) might be a good place to track this
