### ISSUE TITLE
Refactor andor controllers

### ISSUE THREAD

**Issue by Relm-Arrowny** [Relm-Arrowny/p99Bluesky#21]
### Goals
- [ ] Remove unnecessary codes. 
- [ ] Clean up python dependencies so that it can be pip and run on beam line with full functionality (run in blueApi). 
- [ ] Clean up documentations. 

### Tasks
- [ ] Combine the two andor controllers into a single controller if possible.  
- [ ] Add and remove python modules in pyproject.toml.
- [ ] Write documentations for existing devices. 
- [ ] Test everything still works.
