### ISSUE TITLE
Setup Athena communication Channels.

### ISSUE THREAD

**Issue by Relm-Arrowny** [Relm-Arrowny/p99Bluesky#3]
### Goals
Acceptance criteria : 
- [x] Able to collect data and control equipment using blueapi/gda with Athena setup

### Tasks
 base on the goals, deduce the tasks required. check them off once they're done
- [x]  Setup/Request Kubernetes cluster
- [x]  Deployment 
- [x]  Test run with sim motors

### Related Resources
General info for Athena setup
https://gitlab.diamond.ac.uk/sscc-docs/developer-guide/-/blob/athena-rose/docs/athena/how-tos/migration.md?ref_type=heads

j20 notes that will be useful
https://github.com/stan-dot/j20-bluesky/wiki/BlueAPI-use-on-J20-workstation-%E2%80%90-from-Iain

**Comment by Relm-Arrowny** [comment]
Did one better able to link device and up load plan

**Comment by Relm-Arrowny** [comment]
Did one better able to link device and up load plan, the charts can be found under p99 software.
