### ISSUE TITLE
Create ophy device for andor2 detctor

### ISSUE THREAD

**Issue by Relm-Arrowny** [Relm-Arrowny/p99Bluesky#5]
## Acceptance Criteria
- [x]  Create an ophy device for Andor2
- [x]  1.  The detector should be stageable 
             Able to change Acquistion setting, exposure time trigger mode, eg things that need to be change during each data collection                     
- [ ]  2.  Should be able to change Andor Diver setting, chip temperature readout time etc.
- [x]  3. Should be able to write data to somewhere.
- [ ]  4. Ability to access arr of the image for data visualisation? 
- [x]  5. should be able to be use in bluesky plan.

### Tasks
- [x]  Test what functionality of the detector has using epic PV, eg does the roi work etc etc.
- [x]  Go through the device on i22 to draw up a proper task list. (see Ref #332) 
- [x] Create the device
- Add extra functionality that needed in drivers like [pilatus_driver.py](https://github.com/bluesky/ophyd-async/blob/main/src/ophyd_async/epics/areadetector/drivers/pilatus_driver.py) 
- A controller much like [pilatus_controller.py](https://github.com/bluesky/ophyd-async/blob/main/src/ophyd_async/epics/areadetector/controllers/pilatus_controller.py) to deal with how the data collection is done setting trigger, count time etc....
- [x] Device unit test
- Controller and drivers test is required. [example](https://github.com/bluesky/ophyd-async/tree/main/tests/epics/areadetector)  
- [x] IRL test
- Should be able to produce images with different exposure time, change all the setting that are required for the image itself.

### Related Resources

https://github.com/DiamondLightSource/dodal/pull/332

**Comment by Relm-Arrowny** [comment]
Things already exist:
Base class for area detector [ad_base.py](https://github.com/bluesky/ophyd-async/blob/main/src/ophyd_async/epics/areadetector/drivers/ad_base.py):
struct DetectorState
Globe DEAULT_GOOD_STATES  
ADBase class with NDArrayBase (which handle the arr part of the detector) setup the signal part of the epicPv
ADBase itself deal with data acquiring 
Globe function start_acquiring_driver_and_ensure_status : 
check status and start acquire data and check status again 
ADBaseShapeProvider just get the shape by overloading ShapeProvider
